# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division_perm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_external',
            field=models.BooleanField(default=False, help_text='Имеет доступ через rest-api', verbose_name='Внешний вызов'),
        ),
        migrations.AddField(
            model_name='employee',
            name='encrypted_secret_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
